# Config file for automatic testing at travis-ci.org
dist: xenial
language: python
env:
  global:
    - COVERALLS_PARALLEL=true
matrix:
  fast_finish: true
  include:
    - name: Check code style
      python: 3.8
      env: TOXENV="run-blackcheck,run-isortcheck"
    - name: Python 3.6
      python: 3.6
      env: TOXENV=py36-test
    - name: Python 3.7
      python: 3.7
      env: TOXENV=py37-test
    - name: Python 3.8
      python: 3.8
      env: TOXENV=py38-test
    - name: Python 3.9
      python: 3.9
      env: TOXENV=py39-test

install:
  # any failure stops the build
  - set -e
  - pip install tox
  - pip freeze
  - printenv
script:
  # any failure stops testing immediately
  - set -e
  - |
    if [[ "${DOCS}" == "true" ]]; then
      tox -e docs
    else
      tox -e $TOXENV
    fi
  - echo "DONE"
after_success:
  # coveralls is prone to random failures (which would fail the Travis job), so we'll handle those silently
  - if [[ "${TOXENV}" =~ test ]]; then tox -e $(echo "${TOXENV}" | sed s/test/runcmd/) -- coveralls -v || echo "Cannot upload to coveralls"; fi
notifications:
  webhooks: https://coveralls.io/webhook
